---
# tasks file for redash
   - name: CHECK DOCKER INSTALLED
     shell: find_dkr=$(docker --version 2>/dev/null); if [ -n "$find_dkr" ]; then echo "is"; else echo "not"; fi;
     register: is_dkr

   - name: CHECK DOCKER-COMPOSE INSTALLED
     shell: find_dkrc=$(docker-compose --version 2>/dev/null); if [ -n "$find_dkrc" ]; then echo "is"; else echo "not"; fi;
     register: is_dkrc

   - block:
      - name: INSTALL yum-utils
        yum:
         name: "{{ item }}"
         state: present
         update_cache: yes
        with_items:
         - yum-utils
         - device-mapper-persistent-data
         - lvm2

      - name: Add Docker repo
        get_url:
          url: https://download.docker.com/linux/centos/docker-ce.repo
          dest: /etc/yum.repos.d/docer-ce.repo

      - name: INSTALL DOCKER
        dnf:
         name: "{{ item }}"
         state: latest
        with_items:
          - containerd.io
          - docker-ce
          - docker-ce-cli
     when: is_dkr.stdout == "not"

   - block:
     - name: INSTALL DOCKER-COMPOSE
       shell: "{{ item }}"
       with_items:
         - curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
         - chmod +x /usr/local/bin/docker-compose
         - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
     when: is_dkrc.stdout == "not"

   - name: MAKE WORKDIR
     file:
       path: /data/redash/current
       state: directory
       mode: 0775
       recurse: yes

   - name: MAKE DB DIRS
     file:
       path: "{{ item }}"
       state: directory
       mode: 0775
     with_items:
       - /data/redash/current/postgres_data
       - /data/redash/current/redis_data

   - name: COPY env.j2
     template: src=env.j2 dest=/data/redash/current/env mode=0775

   - name: COPY docker-compose.yml
     copy: src=docker-compose.yml dest=/data/redash/current mode=0775

   - name: MAKE DOCKER START
     service: name=docker state=started enabled=yes
     tags: update_db

   - name: UP docker-compose
     shell: cd /data/redash/current && docker-compose -p redash up -d

   - name: DUMP actual database
     shell: cd /data/redash/current && docker-compose -p redash exec postgres bash -c 'PGPASSWORD={{ redash_pg_password }} /usr/local/bin/pg_dump -c -Fc -h {{ redash_pg_host }} -p 5432 -U {{ redash_pg_user }} -d {{ redash_pg_db }} > /tmp/postgres.dmp'
     tags: update_db

   - pause:
       minutes: 1
     tags: update_db

   - name: RESTART docker-compose
     shell: cd /data/redash/current && docker-compose -p redash restart
     tags: update_db

   - name: RESTORE actual database
     shell: cd /data/redash/current && docker-compose -p redash exec postgres bash -c '/usr/local/bin/pg_restore -c --if-exists -U postgres -d postgres < /tmp/postgres.dmp'
     ignore_errors: yes
     tags: update_db

   - pause:
       minutes: 1
     tags: update_db

   - name: MODIFY postygresql.conf
     shell: "{{ item }}"
     with_items:
        - echo 'shared_buffers = 512MB' >> /data/redash/current/postgres_data/postgresql.conf
        - echo 'work_mem = 64MB' >> /data/redash/current/postgres_data/postgresql.conf
        - echo 'maintenance_work_mem = 128MB' >> /data/redash/current/postgres_data/postgresql.conf
        - echo 'bgwriter_delay = 100ms' >> /data/redash/current/postgres_data/postgresql.conf
        - echo 'bgwriter_lru_maxpages = 1000' >> /data/redash/current/postgres_data/postgresql.conf
        - echo 'bgwriter_lru_multiplier = 5.0' >> /data/redash/current/postgres_data/postgresql.conf
        - echo 'checkpoint_timeout = 30min' >> /data/redash/current/postgres_data/postgresql.conf
        - echo 'autovacuum_vacuum_scale_factor = 0.02' >> /data/redash/current/postgres_data/postgresql.conf
        - echo 'autovacuum_analyze_scale_factor = 0.01' >> /data/redash/current/postgres_data/postgresql.conf
        - echo 'autovacuum_vacuum_cost_delay = 5ms' >> /data/redash/current/postgres_data/postgresql.conf

   - name: DELETE /tmp/postgres.dmp
     shell: cd /data/redash/current && docker-compose -p redash exec postgres bash -c 'rm -rf /tmp/postgres.dmp'
     tags: update_db

   - name: RESTART docker-compose
     shell: cd /data/redash/current && docker-compose -p redash stop && docker-compose -p redash start
     tags: update_db
