version: '2'
services:
  server:
    image: redash/redash:8.0.0.b32245
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "50001:5000"
    env_file: /data/redash/current/env
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    image: redash/redash:8.0.0.b32245
    command: scheduler
    env_file: /data/redash/current/env
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
    restart: always
  scheduled_worker:
    image: redash/redash:8.0.0.b32245
    command: worker
    env_file: /data/redash/current/env
    environment:
      QUEUES: "scheduled_queries"
      WORKERS_COUNT: 1
    restart: always
  adhoc_worker:
    image: redash/redash:8.0.0.b32245
    command: worker
    env_file: /data/redash/current/env
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 4
  redis:
    image: redis:3.0-alpine
    volumes:
      - /data/redash/current/redis_data:/data
    restart: always
  postgres:
    image: postgres:9.5.6-alpine
    volumes:
      - /data/redash/current/postgres_data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "81:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
