version: '2'
services:
  server:
    image: redash/redash:10.1.0.b50633
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    env_file: /data/redash/current/env
    environment:
      REDASH_WEB_WORKERS: 10
  scheduler:
    image: redash/redash:10.1.0.b50633
    command: scheduler
    env_file: /data/redash/current/env
    #environment:
    #  QUEUES: "celery"
    #  WORKERS_COUNT: 1
    restart: always
  scheduled_worker:
    image: redash/redash:10.1.0.b50633
    command: worker
    env_file: /data/redash/current/env
    environment:
      QUEUES: "scheduled_queries"
      WORKERS_COUNT: 1
    restart: always
  adhoc_worker:
    image: redash/redash:10.1.0.b50633
    command: worker
    env_file: /data/redash/current/env
    environment:
      QUEUES: "queries,celery,schemas,periodic,default,emails"
      WORKERS_COUNT: 12
  worker:
    image: redash/redash:10.1.0.b50633
    command: worker
    env_file: /data/redash/current/env
    environment:
      QUEUES: "periodic,emails,default"
      WORKERS_COUNT: 1
  redis:
    image: redis:5.0.14-alpine
    volumes:
      - /data/redash/current/redis_data:/data
    restart: always
  postgres:
    image: postgres:9.5.6-alpine
    volumes:
      - /data/redash/current/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "81:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
